# Generated by Django 5.2.6 on 2025-09-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('can_confirm_order', 'Can confirm order')]},
        ),
        migrations.AlterUniqueTogether(
            name='rewardredemption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='ranking_point_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ranking_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='rewardredemption',
            unique_together={('user', 'reward', 'status')},
        ),
    ]
